#!/usr/bin/env python3
"""Turn `lassip --help` into the LaTeX option reference.

The manual's option list is generated rather than written, so it cannot drift
from the binary the way the v1.1.2 PDF did.

    python3 doc/gen-options.py src/lassip > doc/options.tex

Reads the program's own help output and emits one description list per help
section, in the order the program prints them.
"""

import re
import subprocess
import sys

# A flag line is a flag name, optionally followed by argument placeholders, then
# a colon. The argument test matters: continuation lines can themselves begin
# with a flag name -- --max-gap's description opens a sentence with
# "--dist-type cm will interpolate across" -- and those must not start a new
# entry. Placeholders are <...> or the literal ... used by list-valued flags.
FLAG = re.compile(r"^(--[a-z0-9-]+(?:\s+(?:<[^>]*>|\.\.\.))*):\s*(.*)$")
SECTION = re.compile(r"^-{4,}(.+?)-{4,}$")


def tex_escape(s):
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                 ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                 ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def mark_flags(s):
    """Wrap flag mentions in \\texttt.

    Needed for correctness, not only for looks: in text mode TeX typesets `--`
    as an en dash, so an unmarked --threads comes out as -threads.
    """
    return re.sub(r"(--[a-z0-9-]+)", r"\\texttt{\1}", s)


def parse(help_text):
    """[(section, [(flag, signature, description, default), ...]), ...]"""
    sections = []
    flags = None
    cur = None

    def close():
        if cur is not None:
            cur[2] = " ".join(cur[2].split())
            flags.append(tuple(cur))

    for raw in help_text.split("\n"):
        line = raw.rstrip()
        m = SECTION.match(line.strip())
        if m:
            close()
            cur = None
            flags = []
            sections.append((m.group(1).strip(), flags))
            continue
        if flags is None:
            continue  # preamble, before the first section
        stripped = line.strip()
        if not stripped:
            continue
        m = FLAG.match(stripped)
        if m:
            close()
            sig = m.group(1)
            name = sig.split()[0]
            cur = [name, sig, m.group(2), None]
            continue
        if cur is None:
            continue
        if stripped.startswith("Default:"):
            cur[3] = stripped[len("Default:"):].strip()
        else:
            cur[2] += " " + stripped
    close()
    return sections


def emit(sections, out):
    for name, flags in sections:
        if not flags:
            continue
        out.write("\\subsection{%s}\n\n" % tex_escape(name))
        out.write("\\begin{description}[style=nextline,leftmargin=0pt,"
                  "font=\\normalfont\\ttfamily]\n")
        for _, sig, desc, default in flags:
            out.write("\\item[%s]\n" % tex_escape(sig))
            out.write("%s\n" % mark_flags(tex_escape(desc)))
            if default is not None:
                shown = default if default else "(empty)"
                out.write("\\\\\\textit{Default:} \\texttt{%s}\n" % tex_escape(shown))
        out.write("\\end{description}\n\n")


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen-options.py <path to lassip binary>")
    help_text = subprocess.run([sys.argv[1], "--help"], capture_output=True,
                               text=True, check=True).stdout
    sections = parse(help_text)
    nflags = sum(len(f) for _, f in sections)
    if nflags < 20:
        sys.exit("gen-options.py: parsed only %d flags from --help, refusing to "
                 "write a truncated reference" % nflags)
    out = sys.stdout
    out.write("%% Generated by doc/gen-options.py from `lassip --help`. Do not edit.\n")
    out.write("%% %d options in %d sections.\n\n" % (nflags, len(sections)))
    emit(sections, out)


if __name__ == "__main__":
    main()
